/**
 * Shared C-ABI contract for the Bridge FFI layer.
 *
 * One Bridge service can cross a language boundary as FUNCTIONS, not just
 * data: the contract is compiled into a C-ABI dynamic library (Rust) and a
 * matching cgo client (Go). This module owns the pieces both sides must
 * agree on — symbol names, the header file, the status codes and the
 * ownership rules — so the generated glue can never drift apart.
 *
 * Wire shape at the boundary:
 * - Every call takes ONE input buffer (JSON of the request type) and
 *   returns a status code plus ONE output buffer (JSON of the response
 *   type, or a `{"error": {"code", "message"}}` body on failure).
 * - Buffers are caller-allocated for input, callee-allocated for output.
 *   The output buffer MUST be released with `<pkg>_free(ptr, len)` — this
 *   is the single ownership rule of the ABI.
 * - Panics NEVER cross the boundary: every entry point is wrapped in
 *   `catch_unwind` and reports `STATUS_PANIC`.
 *
 * Status codes (int32, stable):
 *   0 ok · 1 panic · 2 invalid request JSON · 3 handler error
 *   4 no handler installed · 5 validation failed
 */

import type { IRPackage, IRService } from '@bridge/core';
import { generatedFile } from './util';
import type { GeneratedFile } from './util';

/** `CreatePayment` → `create_payment` (mirrors @bridge/generators naming). */
export function camelToLowerSnake(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
}

/** Crate name for a package (`payments.v1` → `bridge-payments-v1`). */
export function rustCrateName(pkg: string, prefix = 'bridge'): string {
  const slug = pkg.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
  return `${prefix}-${slug}`;
}

/** Stable C-ABI status codes shared by every generated library. */
export const FFI_STATUS = {
  ok: 0,
  panic: 1,
  invalidJson: 2,
  handlerError: 3,
  noHandler: 4,
  validationFailed: 5,
} as const;

/** Rust crate name for the FFI library of a package. */
export function ffiCrateName(packageName: string): string {
  return rustCrateName(packageName, 'bridge') + '-ffi';
}

/** The `lib` name (crate name with dashes → underscores). */
export function ffiLibName(packageName: string): string {
  return ffiCrateName(packageName).replace(/-/g, '_');
}

/** Sanitized C identifier for a package (`payments.v1` → `payments_v1`). */
export function cSymbolPackage(packageName: string): string {
  return packageName.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
}

/** C symbol for one service method. */
export function methodSymbol(packageName: string, service: string, method: string): string {
  return `bridge_${cSymbolPackage(packageName)}_${camelToLowerSnake(service)}_${camelToLowerSnake(method)}_call`;
}

/** C symbol for the buffer-free function of a package. */
export function freeSymbol(packageName: string): string {
  return `bridge_${cSymbolPackage(packageName)}_free`;
}

/** C symbol for installing the generated demo handlers. */
export function demoHandlerSymbol(packageName: string): string {
  return `bridge_${cSymbolPackage(packageName)}_install_demo_handlers`;
}

/** Echo symbol for a package. */
export function echoSymbol(packageName: string): string {
  return `bridge_${cSymbolPackage(packageName)}_echo_call`;
}

/** The header file path inside the Rust crate. */
export function headerPath(packageName: string): string {
  return `include/bridge_${cSymbolPackage(packageName)}.h`;
}

/** Emit the shared C header for a package's services. */
export function cHeaderFile(ir: IRPackage): GeneratedFile {
  const pkg = cSymbolPackage(ir.name);
  const lines: string[] = [];
  lines.push(`// ${headerPath(ir.name)} — C ABI for the ${ir.name} Bridge contract.`);
  lines.push('// Shared by the Rust cdylib (definitions) and the Go cgo client (declaration).');
  lines.push('// Code generated by bridge DO NOT EDIT.');
  lines.push(`#ifndef BRIDGE_${pkg.toUpperCase()}_H`);
  lines.push(`#define BRIDGE_${pkg.toUpperCase()}_H`);
  lines.push('');
  lines.push('#include <stddef.h>');
  lines.push('#include <stdint.h>');
  lines.push('');
  lines.push('/* Status codes: 0 ok, 1 panic, 2 invalid request JSON, 3 handler error,');
  lines.push('   4 no handler installed, 5 validation failed. */');
  for (const { service, method } of sortedServiceMethods(ir)) {
    lines.push(
      `int32_t ${methodSymbol(ir.name, service.name, method.name)}(` +
        'const uint8_t* input, uintptr_t input_len, ' +
        'uint8_t** output, uintptr_t* output_len);',
    );
  }
  lines.push(`int32_t ${echoSymbol(ir.name)}(const uint8_t* input, uintptr_t input_len, uint8_t** output, uintptr_t* output_len);`);
  lines.push(`void ${freeSymbol(ir.name)}(uint8_t* ptr, uintptr_t len);`);
  lines.push(`int32_t ${demoHandlerSymbol(ir.name)}(void);`);
  lines.push('');
  lines.push('#endif');
  lines.push('');
  return generatedFile(headerPath(ir.name), lines.join('\n'));
}

/** The Go build tag that gates cgo-dependent verification tests. */
export const GO_VERIFY_TAG = 'bridge_ffi_verify';

/** Collect the service methods a package exposes (defensively sorted). */
export function sortedServiceMethods(
  ir: IRPackage,
): Array<{ service: IRService; method: IRService['methods'][number] }> {
  const out: Array<{ service: IRService; method: IRService['methods'][number] }> = [];
  for (const service of [...ir.services].sort((a, b) => (a.name < b.name ? -1 : 1))) {
    for (const method of [...service.methods].sort((a, b) => (a.name < b.name ? -1 : 1))) {
      out.push({ service, method });
    }
  }
  return out;
}

