/**
 * Small shared utilities for the FFI generator (local copies so the
 * package stays decoupled from the generators' internals).
 */

/** A generated file: relative POSIX path (no leading `./`) + content. */
export interface GeneratedFile {
  readonly path: string;
  readonly content: string;
}

/**
 * Creates a GeneratedFile with a normalized path: relative, POSIX-style,
 * no leading `./`, no duplicate slashes — part of the determinism
 * guarantee.
 */
export function generatedFile(path: string, content: string): GeneratedFile {
  const normalized = path
    .replace(/\\/g, '/')
    .replace(/^\.\//, '')
    .replace(/\/{2,}/g, '/')
    .replace(/\/$/, '');
  return { path: normalized, content };
}

/** Joins non-empty blocks with a blank line. */
export function joinBlocks(blocks: string[]): string {
  return blocks.filter((block) => block.length > 0).join('\n\n');
}

/** The canonical generated-file header line. */
export const GENERATED_MARKER = 'Code generated by bridge DO NOT EDIT.';

/** Header block for a generated FFI file. */
export function fileHeader(commentPrefix: string, packageName: string, extra: string[] = []): string {
  const lines = [
    GENERATED_MARKER,
    'Generator version: 0.1.0',
    `Package: ${packageName}`,
    ...extra,
  ];
  return lines.map((line) => `${commentPrefix} ${line}`).join('\n');
}
