/**
 * Generator test suite: per-language structure, determinism, and
 * executable-output verification (Python ast.parse, TS transpile).
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, readdirSync, existsSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { generate, GENERATOR_VERSION } from '../index';
import { makePaymentsIR, makeMinimalIR } from './fixtures';
import type { GeneratedFile } from '../gen/input';

const ir = makePaymentsIR();

function byPath(files: GeneratedFile[], path: string): GeneratedFile {
  const file = files.find((f) => f.path === path);
  assert.ok(file !== undefined, `expected generated file ${path}`);
  return file;
}

function commonHeader(content: string): void {
  assert.ok(
    /^(\/\/|#)? ?Code generated by bridge DO NOT EDIT\./m.test(content),
    'missing DO-NOT-EDIT header',
  );
  assert.ok(content.includes(`Generator version: ${GENERATOR_VERSION}`), 'missing generator version');
  assert.ok(content.includes('Package: payments.v1'), 'missing package name');
  assert.ok(!content.includes('TODO'), 'generated output must not contain TODO');
}

test('Go: expected file list and structure', () => {
  const files = generate(ir, { language: 'go' });
  const paths = files.map((f) => f.path).sort();
  assert.deepEqual(paths, [
    'enums.go', 'events.go', 'go.mod', 'roundtrip_test.go', 'services.go', 'types.go', 'validate.go',
  ]);
  const goMod = byPath(files, 'go.mod');
  assert.match(goMod.content, /^module bridge\/generated\/payments_v1$/m);
  assert.match(goMod.content, /^go 1\.22$/m);
  const types = byPath(files, 'types.go');
  commonHeader(types.content);
  assert.match(types.content, /type Money struct {/);
  assert.match(types.content, /json:"amount"/);
  // Exported CamelCase with initialism preserved + snake wire tag
  assert.match(types.content, /CustomerEmail string ` ?json:"customer_email"`/);
  // Reserved-word escape check: Type as field name for `type`
  assert.match(types.content, /json:"type"/);
  const enums = byPath(files, 'enums.go');
  assert.match(enums.content, /type Status string/);
  assert.match(enums.content, /func ParseStatus\(value string\) \(Status, error\)/);
  const validate = byPath(files, 'validate.go');
  assert.match(validate.content, /func \(m Money\) Validate\(\) error/);
  const services = byPath(files, 'services.go');
  assert.match(services.content, /type PaymentsServer interface {/);
  assert.match(services.content, /func NewPaymentsJSONClient/);
  for (const file of files) commonHeader(file.content);
});

test('Rust: Cargo.toml, serde derives, deterministic collections', () => {
  const files = generate(ir, { language: 'rust' });
  const paths = files.map((f) => f.path).sort();
  assert.deepEqual(paths, [
    'Cargo.toml', 'src/enums.rs', 'src/events.rs', 'src/lib.rs', 'src/services.rs', 'src/types.rs', 'src/validate.rs', 'tests/roundtrip.rs',
  ]);
  const cargo = byPath(files, 'Cargo.toml');
  assert.match(cargo.content, /^name = "bridge-payments-v1"$/m);
  assert.match(cargo.content, /serde = \{ version = "1", features = \["derive"\] \}/);
  const types = byPath(files, 'src/types.rs');
  commonHeader(types.content);
  assert.match(types.content, /#\[derive\(.*Serialize/);
  assert.match(types.content, /pub struct Money \{/);
  assert.match(types.content, /BTreeMap</);
  assert.match(types.content, /BTreeSet</);
  // Optional fields
  assert.match(types.content, /pub refund: Option<Money>/);
  // Cross-package opaque alias
  assert.match(types.content, /pub type LoyaltyProfile = serde_json::Value/);
  const validate = byPath(files, 'src/validate.rs');
  assert.match(validate.content, /pub fn validate\(&self\) -> Result<\(\), ValidationError>/);
  assert.match(validate.content, /pattern validation not supported in generated Rust v1/);
  for (const file of files) commonHeader(file.content);
});

test('TypeScript: project files, wireName escape, validators, client factory', () => {
  const files = generate(ir, { language: 'typescript' });
  const paths = files.map((f) => f.path).sort();
  assert.deepEqual(paths, [
    'package.json', 'src/enums.ts', 'src/events.ts', 'src/index.ts',
    'src/services.ts', 'src/types.ts', 'src/validate.ts', 'tsconfig.json',
  ]);
  const pkg = byPath(files, 'package.json');
  const parsed = JSON.parse(pkg.content) as { name: string; license: string };
  assert.equal(parsed.name, '@generated/payments.v1');
  assert.ok(Array.isArray((JSON.parse(pkg.content) as Record<string, unknown>)['//']), 'header block missing');
  const types = byPath(files, 'src/types.ts');
  commonHeader(types.content);
  assert.match(types.content, /export interface Money \{/);
  assert.match(types.content, /tags\?: Set<string>/);
  assert.match(types.content, /@wireName "type"/);
  const validate = byPath(files, 'src/validate.ts');
  assert.match(validate.content, /export function validateMoney\(value: unknown\): string\[\]/);
  assert.match(validate.content, /export function isMoney\(value: unknown\): value is Money/);
  const services = byPath(files, 'src/services.ts');
  assert.match(services.content, /export interface PaymentsClient \{/);
  assert.match(services.content, /export function createPaymentsClient\(/);
  const index = byPath(files, 'src/index.ts');
  assert.match(index.content, /export \* from '\.\/types';/);
  for (const file of files) {
    if (file.path === 'package.json' || file.path === 'tsconfig.json') continue; // JSON cannot carry comments
    commonHeader(file.content);
  }
});

test('Python: syntax-checked output with expected modules', () => {
  const files = generate(ir, { language: 'python' });
  const paths = files.map((f) => f.path).sort();
  assert.deepEqual(paths, [
    'payments_v1/__init__.py', 'payments_v1/enums.py', 'payments_v1/events.py',
    'payments_v1/models.py', 'payments_v1/services.py', 'payments_v1/validation.py',
    'pyproject.toml',
  ]);
  const pyproject = byPath(files, 'pyproject.toml');
  assert.match(pyproject.content, /^name = "bridge-payments-v1"$/m);
  assert.match(pyproject.content, /^dependencies = \[\]$/m);
  const models = byPath(files, 'payments_v1/models.py');
  commonHeader(models.content);
  assert.match(models.content, /@dataclass/);
  assert.match(models.content, /class Money:/);
  assert.match(models.content, /class Resolution:/);
  assert.match(models.content, /LoyaltyProfile = Any/);
  assert.match(models.content, /OrderId = str/);
  const enums = byPath(files, 'payments_v1/enums.py');
  assert.match(enums.content, /class Status\(str, enum\.Enum\):/);
  const services = byPath(files, 'payments_v1/services.py');
  assert.match(services.content, /class PaymentsClient:/);
  const init = byPath(files, 'payments_v1/__init__.py');
  assert.match(init.content, /__all__ = \[/);
  for (const file of files) commonHeader(file.content);
});

test('Python: generated code parses with ast.parse and round-trips functionally', () => {
  const files = generate(ir, { language: 'python' });
  const dir = mkdtempSync(join(tmpdir(), 'bridge-pygen-'));
  try {
    for (const file of files) {
      const target = join(dir, file.path);
      execFileSync('mkdir', ['-p', join(dir, 'payments_v1')]);
      // Write with the module layout preserved
      const fsWrite = (p: string, c: string) => require('node:fs').writeFileSync(p, c);
      fsWrite(target, file.content);
    }
    // Syntax check every module
    for (const file of files) {
      if (!file.path.endsWith('.py')) continue;
      execFileSync('python3', [
        '-c', 'import ast,sys; ast.parse(open(sys.argv[1]).read())', join(dir, file.path),
      ]);
    }
    // Functional round-trip inside the generated package
    const script = `
import sys
sys.path.insert(0, ${JSON.stringify(dir)})
import payments_v1 as m
money = m.Money(amount="10.00", currency="USD")
assert m.Money.from_dict(money.to_dict()) == money
order = m.Order(
    order_id="123e4567-e89b-12d3-a456-426614174000", version=1,
    status=m.Status.CAPTURED, amount=m.Money(amount="5.00", currency="EUR"),
    lines=[], created_at="2026-01-01T00:00:00Z", tags={"a","b"}, metadata={"x":"1"})
assert m.Order.from_dict(order.to_dict()) == order
assert order.to_dict()["tags"] == ["a","b"]  # set -> sorted JSON array
assert len(m.validate_Money(m.Money(amount="abc", currency="US"))) == 2
r = m.Resolution.refund(money)
assert m.Resolution.from_dict(r.to_dict()) == r
ev = m.PaymentFailed(payment_id="123e4567-e89b-12d3-a456-426614174000", reason="declined")
meta = m.BridgeEventMeta(id="evt-1", source="test://payments", time="2026-01-01T00:00:00Z")
env = m.encode_payment_failed(ev, meta)
assert env["type"] == "payments.v1.PaymentFailed" and env["specversion"] == "1.0"
decoded, dmeta = m.decode_payment_failed(env)
assert decoded == ev and dmeta == meta
seen = []
d = m.BridgeEventDispatcher()
m.register_payment_failed(d, lambda payload, meta2: seen.append(payload))
d.dispatch(env)
assert seen == [ev]
print("PY-OK")
`;
    const out = execFileSync('python3', ['-c', script]).toString().trim();
    assert.equal(out, 'PY-OK');
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('TypeScript: generated code transpiles with zero errors', () => {
  // typescript is available as a devDependency of the monorepo
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const ts = require('typescript') as typeof import('typescript');
  const files = generate(ir, { language: 'typescript' });
  for (const file of files) {
    if (!file.path.endsWith('.ts')) continue;
    const result = ts.transpileModule(file.content, {
      compilerOptions: { target: ts.ScriptTarget.ES2022, strict: true },
      reportDiagnostics: true,
      fileName: file.path,
    });
    const errors = (result.diagnostics ?? []).filter(
      (d) => d.category === ts.DiagnosticCategory.Error,
    );
    assert.equal(
      errors.length,
      0,
      `${file.path}: ${errors
        .map((d) => ts.flattenDiagnosticMessageText(d.messageText, ' '))
        .join('; ')}`,
    );
  }
});

test('Go: braces balance in every file', () => {
  const files = generate(ir, { language: 'go' });
  for (const file of files) {
    if (!file.path.endsWith('.go')) continue;
    let balance = 0;
    for (const ch of file.content) {
      if (ch === '{') balance++;
      if (ch === '}') balance--;
    }
    assert.equal(balance, 0, `${file.path} has unbalanced braces`);
  }
});

test('Rust: braces balance in every file', () => {
  const files = generate(ir, { language: 'rust' });
  for (const file of files) {
    if (!file.path.endsWith('.rs')) continue;
    let balance = 0;
    for (const ch of file.content) {
      if (ch === '{') balance++;
      if (ch === '}') balance--;
    }
    assert.equal(balance, 0, `${file.path} has unbalanced braces`);
  }
});


test('Java: expected file list and structure', () => {
  const files = generate(ir, { language: 'java' });
  const paths = files.map((f) => f.path).sort();
  assert.deepEqual(paths, [
    'pom.xml',
    'src/main/java/bridge/payments/v1/Address.java',
    'src/main/java/bridge/payments/v1/BridgeEvents.java',
    'src/main/java/bridge/payments/v1/BridgeJson.java',
    'src/main/java/bridge/payments/v1/BridgeValidation.java',
    'src/main/java/bridge/payments/v1/Cart.java',
    'src/main/java/bridge/payments/v1/CreatePaymentRequest.java',
    'src/main/java/bridge/payments/v1/Customer.java',
    'src/main/java/bridge/payments/v1/GetPaymentRequest.java',
    'src/main/java/bridge/payments/v1/LegacyPayment.java',
    'src/main/java/bridge/payments/v1/Money.java',
    'src/main/java/bridge/payments/v1/Order.java',
    'src/main/java/bridge/payments/v1/OrderLine.java',
    'src/main/java/bridge/payments/v1/Payment.java',
    'src/main/java/bridge/payments/v1/PaymentMethod.java',
    'src/main/java/bridge/payments/v1/PaymentsClient.java',
    'src/main/java/bridge/payments/v1/PaymentsHttpServer.java',
    'src/main/java/bridge/payments/v1/Resolution.java',
    'src/main/java/bridge/payments/v1/Status.java',
    'src/test/java/bridge/payments/v1/RoundTripTest.java',
  ]);
  const pom = byPath(files, 'pom.xml');
  // XML cannot carry a line comment: the header is an XML comment block.
  assert.match(pom.content, /<!-- Code generated by bridge DO NOT EDIT\./);
  const money = byPath(files, 'src/main/java/bridge/payments/v1/Money.java');
  commonHeader(money.content);
  assert.match(money.content, /public final class Money \{/);
  assert.match(money.content, /private final String amount;/);
  assert.match(money.content, /out\.put\("amount", this\.amount\);/);
  assert.match(money.content, /public static Money fromDict\(Map<String, Object> data\)/);
  assert.match(money.content, /return BridgeValidation\.validateMoney\(this\);/);
  const status = byPath(files, 'src/main/java/bridge/payments/v1/Status.java');
  assert.match(status.content, /public enum Status \{/);
  assert.match(status.content, /public static Status fromWire\(String value\)/);
  // Alias (OrderId) substitutes the underlying type: a plain String field.
  const payment = byPath(files, 'src/main/java/bridge/payments/v1/Payment.java');
  commonHeader(payment.content);
  assert.match(payment.content, /private final String orderId;/);
  // Cross-package opaque reference is an Object passthrough.
  assert.match(payment.content, /Optional<Object> loyaltyProfile;/);
  // Optional primitives use boxed Optional types.
  const orderLine = byPath(files, 'src/main/java/bridge/payments/v1/OrderLine.java');
  assert.match(orderLine.content, /Optional<Double> weightKg;/);
  // Sets sort for deterministic wire output.
  const order = byPath(files, 'src/main/java/bridge/payments/v1/Order.java');
  assert.match(order.content, /Collections\.sort/);
  // Wire names stay snake_case.
  assert.match(payment.content, /out\.put\("customer_email", /);
  // Reserved-word escape: `type` field becomes type_ member, wire name kept.
  assert.match(payment.content, /out\.put\("type", /);
  const client = byPath(files, 'src/main/java/bridge/payments/v1/PaymentsClient.java');
  assert.match(client.content, /public Payment createPayment\(CreatePaymentRequest request\)/);
  assert.match(client.content, /payments\.v1\/Payments\/CreatePayment/);
  const server = byPath(files, 'src/main/java/bridge/payments/v1/PaymentsHttpServer.java');
  assert.match(server.content, /interface PaymentsHandler/);
  assert.match(server.content, /case "already_exists":/);
  const events = byPath(files, 'src/main/java/bridge/payments/v1/BridgeEvents.java');
  assert.match(events.content, /PAYMENT_CAPTURED_TYPE = "payments\.v1\.PaymentCaptured"/);
  assert.match(events.content, /class PaymentCapturedPayload/);
  for (const file of files) {
    if (file.path === 'pom.xml') continue; // XML header checked above
    commonHeader(file.content);
  }
});

test('C#: expected file list and structure', () => {
  const files = generate(ir, { language: 'csharp' });
  const paths = files.map((f) => f.path).sort();
  assert.deepEqual(paths, [
    'Bridge.Payments.V1.csproj',
    'Enums.cs', 'Events.cs', 'Models.cs', 'RoundTripTest.cs',
    'Services.cs', 'Validation.cs',
  ]);
  const csproj = byPath(files, 'Bridge.Payments.V1.csproj');
  assert.match(csproj.content, /<TargetFramework>net8\.0<\/TargetFramework>/);
  assert.match(csproj.content, /<!-- Code generated by bridge DO NOT EDIT\./);
  const models = byPath(files, 'Models.cs');
  commonHeader(models.content);
  assert.match(models.content, /public sealed class Money/);
  assert.match(models.content, /public Dictionary<string, object> ToDict\(\)/);
  assert.match(models.content, /public static Money FromDict\(JsonElement root\)/);
  // Alias substitution: OrderId field is a plain string property.
  assert.match(models.content, /public string OrderId \{ get; set; \}/);
  // Optional primitives are nullable value types.
  assert.match(models.content, /public double\? WeightKg \{ get; set; \}/);
  // Cross-package opaque reference is a JsonElement passthrough.
  assert.match(models.content, /public System\.Text\.Json\.JsonElement\? LoyaltyProfile/);
  // Structural equality helpers referenced by generated Equals.
  assert.match(models.content, /BridgeJson\.DeepEquals\(this\.Amount, other\.Amount\)/);
  const enums = byPath(files, 'Enums.cs');
  assert.match(enums.content, /public readonly record struct Status/);
  assert.match(enums.content, /public static Status Parse\(string value\)/);
  const validation = byPath(files, 'Validation.cs');
  assert.match(validation.content, /public static List<string> ValidateMoney\(Money value\)/);
  assert.match(validation.content, /private static readonly Regex PAddressPostalCode/);
  const services = byPath(files, 'Services.cs');
  assert.match(services.content, /public Payment CreatePayment\(CreatePaymentRequest request\)/);
  assert.match(services.content, /"already_exists" => 409/);
  const events = byPath(files, 'Events.cs');
  assert.match(events.content, /PaymentCapturedType = "payments\.v1\.PaymentCaptured"/);
  assert.match(events.content, /public sealed class PaymentCapturedPayload/);
  const roundtrip = byPath(files, 'RoundTripTest.cs');
  assert.match(roundtrip.content, /public static void Main\(\)/);
  for (const file of files) {
    if (file.path === 'Bridge.Payments.V1.csproj') continue; // XML header checked above
    commonHeader(file.content);
  }
});

/** Strips string/char literals so brace counting ignores their contents. */
function stripLiterals(content: string): string {
  return content
    .replace(/"(?:[^"\\\n]|\\.)*"/g, '""')
    .replace(/'(?:[^'\\\n]|\\.)*'/g, "''")
    .replace(/\/\/[^\n]*/g, '');
}

test('Java: braces balance in every file', () => {
  const files = generate(ir, { language: 'java' });
  for (const file of files) {
    if (!file.path.endsWith('.java')) continue;
    let balance = 0;
    for (const ch of stripLiterals(file.content)) {
      if (ch === '{') balance++;
      if (ch === '}') balance--;
    }
    assert.equal(balance, 0, `${file.path} has unbalanced braces`);
  }
});

test('C#: braces balance in every file', () => {
  const files = generate(ir, { language: 'csharp' });
  for (const file of files) {
    if (!file.path.endsWith('.cs')) continue;
    let balance = 0;
    for (const ch of stripLiterals(file.content)) {
      if (ch === '{') balance++;
      if (ch === '}') balance--;
    }
    assert.equal(balance, 0, `${file.path} has unbalanced braces`);
  }
});

test('minimal package generates a compact file set (java, csharp)', () => {
  const java = generate(makeMinimalIR(), { language: 'java' });
  assert.deepEqual(java.map((f) => f.path).sort(), [
    'pom.xml',
    'src/main/java/bridge/tiny/v1/BridgeJson.java',
    'src/main/java/bridge/tiny/v1/BridgeValidation.java',
    'src/main/java/bridge/tiny/v1/Ping.java',
    'src/test/java/bridge/tiny/v1/RoundTripTest.java',
  ]);
  const cs = generate(makeMinimalIR(), { language: 'csharp' });
  assert.deepEqual(cs.map((f) => f.path).sort(), [
    'Bridge.Tiny.V1.csproj', 'Models.cs', 'RoundTripTest.cs', 'Validation.cs',
  ]);
});

test('determinism: generate twice is byte-identical', () => {
  for (const language of ['go', 'rust', 'typescript', 'python', 'java', 'csharp'] as const) {
    const a = generate(ir, { language });
    const b = generate(ir, { language });
    assert.deepEqual(a, b, `repeat generation differs for ${language}`);
  }
});

test('determinism: reversed input arrays produce identical output', () => {
  const reversed = {
    ...ir,
    types: [...ir.types].reverse(),
    services: [...ir.services].reverse(),
    events: [...ir.events].reverse(),
  };
  for (const language of ['go', 'rust', 'typescript', 'python', 'java', 'csharp'] as const) {
    const a = generate(ir, { language });
    const b = generate(reversed, { language });
    assert.deepEqual(
      a,
      b,
      `reversed input order changed output for ${language}`,
    );
  }
});

test('options: services and events can be disabled', () => {
  const minimal = makeMinimalIR();
  const py = generate(minimal, { language: 'python' });
  assert.ok(!py.some((f) => f.path.includes('services') || f.path.includes('events')));
  const ts = generate(minimal, { language: 'typescript' });
  assert.ok(!ts.some((f) => f.path.endsWith('services.ts') || f.path.endsWith('events.ts')));
  const go = generate(minimal, { language: 'go' });
  assert.ok(!go.some((f) => f.path === 'services.go' || f.path === 'events.go'));
  const rust = generate(minimal, { language: 'rust' });
  assert.ok(!rust.some((f) => f.path.endsWith('services.rs') || f.path.endsWith('events.rs')));
});

test('minimal package generates a compact file set', () => {
  const files = generate(makeMinimalIR(), { language: 'python' });
  const paths = files.map((f) => f.path).sort();
  assert.deepEqual(paths, [
    'pyproject.toml', 'tiny_v1/__init__.py', 'tiny_v1/models.py', 'tiny_v1/validation.py',
  ]);
});

test('paths are normalized relative POSIX paths', () => {
  for (const language of ['go', 'rust', 'typescript', 'python', 'java', 'csharp'] as const) {
    for (const file of generate(ir, { language })) {
      assert.ok(!file.path.startsWith('/'), `absolute path: ${file.path}`);
      assert.ok(!file.path.startsWith('./'), `leading ./ in ${file.path}`);
      assert.ok(!file.path.includes('\\\\'), `backslash in ${file.path}`);
    }
  }
});
