/**
 * FFI generator tests: structure, determinism and ABI consistency across
 * the Rust and Go sides (symbol agreement, header agreement, status
 * codes).
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { makePaymentsIR, makeMinimalIR } from '@bridge/generators/dist/test/fixtures.js';
import type { IRPackage } from '@bridge/core';
import {
  FFI_STATUS,
  cHeaderFile,
  echoSymbol,
  ffiCrateName,
  ffiLibName,
  freeSymbol,
  generateFfi,
  methodSymbol,
} from '../index';
import type { GeneratedFile } from '../util';

const ir = makePaymentsIR();

function byPath(files: GeneratedFile[], path: string): GeneratedFile {
  const file = files.find((f) => f.path === path);
  assert.ok(file !== undefined, `expected generated file ${path}`);
  return file;
}

function commonHeader(content: string): void {
  assert.match(content, /Code generated by bridge DO NOT EDIT\./);
  assert.ok(!content.includes('TODO'), 'generated output must not contain TODO');
}

test('rust-ffi: expected file list and structure', () => {
  const files = generateFfi(ir, { target: 'rust-ffi' });
  const paths = files.map((f) => f.path).sort();
  assert.deepEqual(paths, [
    'Cargo.toml',
    'include/bridge_payments_v1.h',
    'src/enums.rs',
    'src/ffi.rs',
    'src/lib.rs',
    'src/types.rs',
    'src/validate.rs',
    'tests/abi.rs',
  ]);
  const cargo = byPath(files, 'Cargo.toml');
  assert.match(cargo.content, /^name = "bridge-payments-v1-ffi"$/m);
  assert.match(cargo.content, /crate-type = \["cdylib", "rlib"\]/);
  const lib = byPath(files, 'src/lib.rs');
  commonHeader(lib.content);
  assert.match(lib.content, /pub struct Handlers \{/);
  assert.match(lib.content, /install_handlers/);
  const ffi = byPath(files, 'src/ffi.rs');
  commonHeader(ffi.content);
  assert.match(ffi.content, /catch_unwind\(AssertUnwindSafe/);
  // One entry point per method with the canonical symbol.
  assert.match(ffi.content, /pub extern "C" fn bridge_payments_v1_payments_create_payment_call\(/);
  assert.match(ffi.content, /pub extern "C" fn bridge_payments_v1_free\(/);
  // Handler presence is checked BEFORE request parsing.
  assert.match(ffi.content, /no_handler/);
  const header = byPath(files, 'include/bridge_payments_v1.h');
  commonHeader(header.content.replace(/^\/\/ /gm, '// '));
  assert.match(header.content, /int32_t bridge_payments_v1_payments_create_payment_call\(/);
  assert.match(header.content, /void bridge_payments_v1_free\(/);
  for (const file of files) {
    if (file.path.endsWith('.h')) continue; // C header style checked above
    if (file.path === 'Cargo.toml') continue; // TOML header is a comment block
    commonHeader(file.content);
  }
});

test('go-ffi: expected file list and structure', () => {
  const files = generateFfi(ir, { target: 'go-ffi' });
  const paths = files.map((f) => f.path).sort();
  assert.deepEqual(paths, [
    'bridge_payments_v1.h',
    'client.go',
    'ffi_verify_test.go',
    'go.mod',
  ]);
  const client = byPath(files, 'client.go');
  commonHeader(client.content);
  assert.match(client.content, /import "C"/);
  assert.match(client.content, /func PaymentsCreatePayment\(request json\.RawMessage\) \(json\.RawMessage, error\)/);
  assert.match(client.content, /C\.bridge_payments_v1_payments_create_payment_call\(/);
  assert.match(client.content, /BridgeCallError/);
  const test = byPath(files, 'ffi_verify_test.go');
  assert.match(test.content, /\/\/go:build bridge_ffi_verify/);
  assert.match(test.content, /TestEchoRoundTrip/);
  const goMod = byPath(files, 'go.mod');
  assert.match(goMod.content, /^module bridge\/generated\/payments_v1\/ffi$/m);
});

test('wasm: expected file list and structure', () => {
  const files = generateFfi(ir, { target: 'wasm' });
  const paths = files.map((f) => f.path).sort();
  assert.deepEqual(paths, [
    'Cargo.toml',
    'index.d.ts',
    'index.ts',
    'src/enums.rs',
    'src/lib.rs',
    'src/types.rs',
    'src/validate.rs',
  ]);
  const lib = byPath(files, 'src/lib.rs');
  commonHeader(lib.content);
  assert.match(lib.content, /wasm_bindgen/);
  assert.match(lib.content, /macro_rules! bridge_wasm_type/);
  assert.match(lib.content, /bridge_wasm_type!\(Money\)/);
  const dts = byPath(files, 'index.d.ts');
  assert.match(dts.content, /static fromJson\(json: string\): MoneyWasm;/);
  const loader = byPath(files, 'index.ts');
  assert.match(loader.content, /export async function loadWasm\(\)/);
});

test('abi: symbols agree between the C header, Rust and Go output', () => {
  const symbol = methodSymbol('payments.v1', 'Payments', 'CreatePayment');
  assert.equal(symbol, 'bridge_payments_v1_payments_create_payment_call');
  const header = cHeaderFile(ir).content;
  const rust = generateFfi(ir, { target: 'rust-ffi' }).find((f) => f.path === 'src/ffi.rs')!.content;
  const go = generateFfi(ir, { target: 'go-ffi' }).find((f) => f.path === 'client.go')!.content;
  for (const { service, method } of [{ service: 'Payments', method: 'CreatePayment' }, { service: 'Payments', method: 'GetPayment' }]) {
    const sym = methodSymbol('payments.v1', service, method);
    assert.ok(header.includes(sym), `header missing ${sym}`);
    assert.ok(rust.includes(sym), `rust missing ${sym}`);
    assert.ok(go.includes(sym), `go missing ${sym}`);
  }
  assert.ok(header.includes(freeSymbol('payments.v1')));
  assert.ok(rust.includes(echoSymbol('payments.v1')));
  assert.ok(go.includes(echoSymbol('payments.v1')));
});

test('status codes are stable across the ABI surface', () => {
  assert.deepEqual(FFI_STATUS, { ok: 0, panic: 1, invalidJson: 2, handlerError: 3, noHandler: 4, validationFailed: 5 });
  const ffi = generateFfi(ir, { target: 'rust-ffi' }).find((f) => f.path === 'src/ffi.rs')!.content;
  assert.match(ffi, /pub const STATUS_OK: i32 = 0;/);
  assert.match(ffi, /pub const STATUS_NO_HANDLER: i32 = 4;/);
});

test('naming: crate, lib and symbol hygiene', () => {
  assert.equal(ffiCrateName('payments.v1'), 'bridge-payments-v1-ffi');
  assert.equal(ffiLibName('payments.v1'), 'bridge_payments_v1_ffi');
});

test('determinism: generate twice is byte-identical for all targets', () => {
  for (const target of ['rust-ffi', 'go-ffi', 'wasm'] as const) {
    const a = generateFfi(ir, { target });
    const b = generateFfi(ir, { target });
    assert.deepEqual(a, b, `repeat generation differs for ${target}`);
  }
});

test('determinism: reversed input arrays produce identical output', () => {
  const reversed: IRPackage = {
    ...ir,
    types: [...ir.types].reverse(),
    services: [...ir.services].reverse(),
    events: [...ir.events].reverse(),
  };
  for (const target of ['rust-ffi', 'go-ffi', 'wasm'] as const) {
    const a = generateFfi(ir, { target });
    const b = generateFfi(reversed, { target });
    assert.deepEqual(a, b, `reversed input order changed output for ${target}`);
  }
});

test('minimal package (no services) still emits the echo probe', () => {
  const minimal = makeMinimalIR();
  for (const target of ['rust-ffi', 'go-ffi'] as const) {
    const files = generateFfi(minimal, { target });
    const symbol = echoSymbol('tiny.v1');
    const body = files.map((f) => f.content).join('\n');
    assert.ok(body.includes(symbol), `${target} missing echo probe for a service-less package`);
  }
});

test('generateServices: false omits method surfaces', () => {
  const files = generateFfi(ir, { target: 'rust-ffi', generateServices: false });
  const ffi = files.find((f) => f.path === 'src/ffi.rs');
  assert.ok(ffi !== undefined);
  assert.ok(!ffi.content.includes('bridge_payments_v1_payments_create_payment_call'));
});

test('wasm: module declarations gated on file presence (enum-less package)', () => {
  const minimal = makeMinimalIR();
  const files = generateFfi(minimal, { target: 'wasm' });
  const paths = files.map((f) => f.path);
  const lib = byPath(files, 'src/lib.rs');
  if (!paths.includes('src/enums.rs')) {
    assert.doesNotMatch(lib.content, /pub mod enums;/, 'lib.rs declares enums module with no enums.rs emitted');
  }
  if (paths.includes('src/types.rs')) {
    assert.match(lib.content, /pub mod types;/);
  }
});
