/**
 * Generated-file headers.
 *
 * EVERY generated file starts with the marker line
 * `Code generated by bridge DO NOT EDIT.` followed by the generator
 * version and the source package name, in the target language's comment
 * syntax. No timestamps, no environment data — output is byte-stable.
 */

import type { TargetLanguage } from './mappings';

/** Current generator version. Keep in sync with the exported constant. */
export const HEADER_GENERATOR_VERSION = '0.1.0';

/** The canonical first line of every generated file. */
export const GENERATED_MARKER = 'Code generated by bridge DO NOT EDIT.';

/**
 * Builds the header block for a generated file.
 *
 * @param language target language (picks the comment syntax)
 * @param packageName dotted Bridge package name, e.g. `payments.v1`
 * @param extra optional extra lines appended after the standard header
 */
export function fileHeader(
  language: TargetLanguage,
  packageName: string,
  extra: string[] = [],
): string {
  const lines = [
    GENERATED_MARKER,
    `Generator version: ${HEADER_GENERATOR_VERSION}`,
    `Package: ${packageName}`,
    ...extra,
  ];
  const prefix = commentPrefix(language);
  // JSON has no comments; the tsconfig.json (JSONC) does. For
  // package.json we emit a `//` key handled by the TS generator instead.
  if (prefix === null) {
    return lines.join('\n');
  }
  return lines.map((line) => `${prefix} ${line}`).join('\n');
}

/** Comment prefix per language; null when the format has no comments. */
export function commentPrefix(language: TargetLanguage): string | null {
  switch (language) {
    case 'go':
    case 'rust':
    case 'typescript':
      return '//';
    case 'python':
      return '#';
  }
}

/**
 * Header lines as a plain string array (used by JSON formats such as
 * package.json, which cannot carry comments; the TS generator embeds
 * them under a top-level `"//"` key).
 */
export function headerLines(packageName: string, extra: string[] = []): string[] {
  return [
    GENERATED_MARKER,
    `Generator version: ${HEADER_GENERATOR_VERSION}`,
    `Package: ${packageName}`,
    ...extra,
  ];
}
