/**
 * @bridge/generators — deterministic code generators for Bridge contracts.
 *
 * Public API:
 * - `generate(ir, options)` → GeneratedFile[]  (pure + byte-deterministic)
 * - `TargetLanguage`, `GeneratedFile`, `GenerateOptions`
 * - `GENERATOR_VERSION`
 *
 * Purity contract: `generate` never reads the clock, the environment, or
 * random state, and never mutates its input. The same IR package always
 * produces byte-identical output — array order of `ir.types` / `ir.services`
 * / `ir.events` is defensively re-sorted inside the generators.
 *
 * Generated file paths are relative POSIX paths without a leading `./`.
 * Every generated file carries the header
 * `Code generated by bridge DO NOT EDIT.` plus the generator version and
 * source package name; no timestamps.
 */

import type { IRPackage } from '@bridge/core';
import type { GeneratorInput, GeneratedFile } from './gen/input';
import { generateGo } from './gen/go';
import { generateRust } from './gen/rust';
import { generateTypeScript } from './gen/typescript';
import { generatePython } from './gen/python';
import type { RenderContext, TargetLanguage } from './mappings';
import { localTypeNames } from './analysis';
import type { GenerateOptions } from './options';

export type { TargetLanguage, GeneratedFile } from './gen/input';
export type { GenerateOptions } from './options';

/** Version of the generator; embedded in every generated file header. */
export const GENERATOR_VERSION = '0.1.0';

/**
 * Generates a full language project from a compiled Bridge IR package.
 *
 * @param ir canonical IR (as produced by `@bridge/core`)
 * @param options target language and knobs
 * @returns files in deterministic order; paths are relative POSIX paths
 */
export function generate(ir: IRPackage, options: GenerateOptions): GeneratedFile[] {
  const packageName = options.packageName ?? ir.name;
  const generateServices = options.generateServices ?? true;
  const generateEvents = options.generateEvents ?? true;

  const input: GeneratorInput = {
    ir,
    language: options.language,
    packageName,
    generateServices,
    generateEvents,
    render: {
      language: options.language,
      packageName,
      localTypeNames: localTypeNames(ir),
    } satisfies RenderContext,
  };

  switch (options.language) {
    case 'go':
      return generateGo(input);
    case 'rust':
      return generateRust(input);
    case 'typescript':
      return generateTypeScript(input);
    case 'python':
      return generatePython(input);
  }
}

/** Re-exported so consumers can generate without depending on core types. */
export type { IRPackage };
