-- 0001_init.sql — initial schema for the Bridge registry service (PostgreSQL driver).
--
-- Conventions:
-- - All tables are prefixed `bridge_` so the service can share a database.
-- - Contract content is stored as JSONB; the `ir` column holds the canonical
--   IR object, `meta` the publish metadata, `imports` the recorded import
--   list (used by dependents/graph queries).
-- - Identity is (org, project, base, version). Immutability is enforced by
--   the primary key plus a hash comparison performed by the driver before
--   insert (identical content replays, different content conflicts).
-- - `time` on audit rows is stored as ISO-8601 UTC text (as generated by the
--   service) so lexicographic ordering/filtering is chronologically correct.

CREATE TABLE IF NOT EXISTS bridge_schema_migrations (
    name       text PRIMARY KEY,
    applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bridge_contracts (
    org          text        NOT NULL,
    project      text        NOT NULL,
    base         text        NOT NULL,
    version      text        NOT NULL,
    package_name text        NOT NULL,
    hash         text        NOT NULL,
    ir           jsonb       NOT NULL,
    meta         jsonb       NOT NULL,
    imports      jsonb       NOT NULL,
    published_at text        NOT NULL,
    published_by text,
    PRIMARY KEY (org, project, base, version)
);

CREATE INDEX IF NOT EXISTS bridge_contracts_org_project_idx
    ON bridge_contracts (org, project, base, version);

CREATE INDEX IF NOT EXISTS bridge_contracts_imports_idx
    ON bridge_contracts USING gin (imports jsonb_path_ops);

CREATE TABLE IF NOT EXISTS bridge_audit (
    id       bigserial PRIMARY KEY,
    time     text       NOT NULL,
    org      text,
    project  text,
    actor    text,
    action   text       NOT NULL,
    contract text,
    version  text,
    ok       boolean    NOT NULL,
    status   integer    NOT NULL,
    ip       text,
    details  jsonb
);

CREATE INDEX IF NOT EXISTS bridge_audit_time_idx     ON bridge_audit (time DESC);
CREATE INDEX IF NOT EXISTS bridge_audit_actor_idx    ON bridge_audit (actor, time DESC);
CREATE INDEX IF NOT EXISTS bridge_audit_action_idx   ON bridge_audit (action, time DESC);
CREATE INDEX IF NOT EXISTS bridge_audit_contract_idx ON bridge_audit (contract, time DESC);
CREATE INDEX IF NOT EXISTS bridge_audit_org_idx      ON bridge_audit (org, time DESC);
