#!/usr/bin/env python3
"""Bridge QA & Production Readiness Report — body PDF (ReportLab).

Cover is rendered separately via html2poster.js and merged with pypdf.
No TOC (moderate-length report) -> SimpleDocTemplate.build per the report brief.
"""
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether,
)

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#f0f0ee')
SECTION_BG    = colors.HexColor('#eaeae8')
CARD_BG       = colors.HexColor('#e9e7e3')
TABLE_STRIPE  = colors.HexColor('#f0f0ef')
HEADER_FILL   = colors.HexColor('#675e43')
COVER_BLOCK   = colors.HexColor('#635b41')
BORDER        = colors.HexColor('#c8c2b0')
ICON          = colors.HexColor('#a58e4c')
ACCENT        = colors.HexColor('#a2842c')
ACCENT_2      = colors.HexColor('#6348b3')
TEXT_PRIMARY  = colors.HexColor('#201f1d')
TEXT_MUTED    = colors.HexColor('#7e7c74')
SEM_SUCCESS   = colors.HexColor('#408958')
SEM_WARNING   = colors.HexColor('#a8894a')
SEM_ERROR     = colors.HexColor('#a75d56')
SEM_INFO      = colors.HexColor('#547493')

OUT = '/home/z/my-project/scripts/qa-report-body.pdf'

# ── Styles ──────────────────────────────────────────────────────────────
H1 = ParagraphStyle('H1', fontName='Helvetica-Bold', fontSize=17, leading=22,
                    textColor=TEXT_PRIMARY, spaceBefore=18, spaceAfter=8)
H2 = ParagraphStyle('H2', fontName='Helvetica-Bold', fontSize=12.5, leading=17,
                    textColor=TEXT_PRIMARY, spaceBefore=12, spaceAfter=5)
BODY = ParagraphStyle('BODY', fontName='Helvetica', fontSize=10, leading=15.5,
                      textColor=TEXT_PRIMARY, alignment=0, spaceAfter=6)
MUTED = ParagraphStyle('MUTED', parent=BODY, textColor=TEXT_MUTED, fontSize=9,
                       leading=13.5)
CELL = ParagraphStyle('CELL', fontName='Helvetica', fontSize=9, leading=12.5,
                      textColor=TEXT_PRIMARY)
CELL_B = ParagraphStyle('CELL_B', parent=CELL, fontName='Helvetica-Bold')
PASS_S = ParagraphStyle('PASS_S', parent=CELL, fontName='Helvetica-Bold',
                        textColor=SEM_SUCCESS)
FAIL_S = ParagraphStyle('FAIL_S', parent=CELL, fontName='Helvetica-Bold',
                        textColor=SEM_ERROR)
WARN_S = ParagraphStyle('WARN_S', parent=CELL, fontName='Helvetica-Bold',
                        textColor=SEM_WARNING)
CODE = ParagraphStyle('CODE', fontName='Courier', fontSize=8.5, leading=12,
                      textColor=TEXT_PRIMARY, backColor=SECTION_BG,
                      borderPadding=4, leftIndent=4, spaceAfter=6)

AVAILABLE = A4[0] - 22*mm - 22*mm  # content width with 22mm margins


def styled_table(data, widths, header=True):
    """Build a table with proportional widths inside the safe area."""
    total = sum(widths)
    cols = [w / total * AVAILABLE for w in widths]
    t = Table(data, colWidths=cols, repeatRows=1 if header else 0)
    style = [
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('GRID', (0, 0), (-1, -1), 0.4, BORDER),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]
    if header:
        style += [
            ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ]
        # header cells need white bold text
    t.setStyle(TableStyle(style))
    return t


def header_row(labels):
    return [Paragraph(f'<font color="white"><b>{l}</b></font>', CELL) for l in labels]


story = []

# ── 1. Executive Summary ────────────────────────────────────────────────
story.append(Paragraph('1. Executive Summary', H1))
story.append(Paragraph(
    'Bridge v0.2.1 has passed a full independent validation pass across product '
    'coverage, code quality, runtime behavior, security, repository hygiene and '
    'documentation. The validation was executed as an adversarial audit: every '
    'completion claim in the repository was re-verified against the actual '
    'running system rather than trusted. Where the audit found defects, each one '
    'was converted into a tracked GitHub issue, implemented on its own branch, '
    'reviewed through a pull request mapped to explicit acceptance criteria, '
    'merged, and then re-verified post-merge.', BODY))
story.append(Paragraph(
    'The final verdict is that the platform is ready for customer onboarding. '
    'The complete journey a customer would follow — writing a contract, '
    'publishing it to the registry service over HTTP with authentication and '
    'tenancy coordinates, and then browsing that contract, its compatibility '
    'reports, its dependency graph and the audit trail in the live dashboard — '
    'was exercised end to end in a real browser during this validation pass. '
    'All nine workspace packages build cleanly, the full suite of 699 tests '
    'passes, lint is at zero warnings, and a 25-step end-to-end acceptance gate '
    'is green from a clean checkout.', BODY))
story.append(Paragraph(
    'One item remains open and it is outside the repository: the GitHub Actions '
    'billing lock on the account prevents CI from running. The lock is an '
    'owner-level billing setting that cannot be lifted through any API; until '
    'the owner raises the Actions spending limit, every push must be verified '
    'locally (exactly as this report documents) and the v0.2.1 tag should not '
    'be cut until the release pipeline can execute. Section 9 lists this and '
    'the other accepted risks honestly.', BODY))

verdict = [
    header_row(['Dimension', 'Result', 'Evidence']),
    [Paragraph('Compiler, generators, compat, registry, CLI, FFI, LSP', CELL),
     Paragraph('PASS', PASS_S),
     Paragraph('699/699 tests; clean-room clone build + test + gate', CELL)],
    [Paragraph('End-to-end acceptance gate (25 steps)', CELL),
     Paragraph('PASS', PASS_S),
     Paragraph('25/25 from clean checkout incl. release binary', CELL)],
    [Paragraph('CLI to registry service over HTTP', CELL),
     Paragraph('PASS', PASS_S),
     Paragraph('Publish/versions/inspect/pull/search with auth + tenancy', CELL)],
    [Paragraph('Live dashboard against real service', CELL),
     Paragraph('PASS', PASS_S),
     Paragraph('Browser-verified: overview, contracts, graph, audit', CELL)],
    [Paragraph('Security (secrets, auth, tamper checks)', CELL),
     Paragraph('PASS', PASS_S),
     Paragraph('History scan clean; fail-closed auth; contentHash tripwire', CELL)],
    [Paragraph('Repository hygiene', CELL),
     Paragraph('PASS', PASS_S),
     Paragraph('18 AI artifacts removed; 27 orphan branches deleted', CELL)],
    [Paragraph('CI (GitHub Actions)', CELL),
     Paragraph('BLOCKED', FAIL_S),
     Paragraph('Account-level billing lock; owner-side action required', CELL)],
]
story.append(KeepTogether(styled_table(verdict, [3.2, 1.1, 4.4])))

# ── 2. Product Coverage ─────────────────────────────────────────────────
story.append(Paragraph('2. Product Coverage', H1))
story.append(Paragraph(
    'Requirements were reconstructed from the full conversation history and '
    'reconciled against the implementation. The platform ships the complete '
    'Phase 1-3 roadmap: the Bridge IDL compiler (lexer, parser, semantic '
    'analysis) producing a frozen, content-addressed canonical IR; six '
    'dependency-free code generators (Go, Rust, TypeScript, Python, Java, C#) '
    'with runtime validators for every constraint; the compatibility engine '
    'with honest SAFE/WARNING/BREAKING/UNKNOWN classification; consumer-aware '
    'impact analysis and CI governance; a local content-addressed registry and '
    'a multi-tenant registry service with OIDC or token auth, signing, rate '
    'limits and an audit log; cross-language serialization round-trip matrices; '
    'a Go-Rust FFI over a C ABI plus a WASM target; a language server; and the '
    'Next.js console. Each of these is covered by tests that pass in this '
    'validation, not merely present in the tree.', BODY))
story.append(Paragraph(
    'Two requirements discovered during this audit were incomplete rather than '
    'missing, and both are now complete. The CLI could not publish to the '
    'registry service over HTTP, which made the canonical user journey '
    'impossible; that integration now exists with full test coverage. The '
    'dashboard live mode had been written against an imagined API contract and '
    'had never worked against the real service; it was rebuilt against the '
    'actual routes with honest data projection. One earlier audit finding was '
    'retracted during this pass: the CI branch filter was never corrupted — '
    'that claim was an artifact of unreliable content rendering, disproven by '
    'byte-independent git blob hashing, and the issue was closed as invalid '
    'with the evidence published.', BODY))

# ── 3. GitHub Work ──────────────────────────────────────────────────────
story.append(Paragraph('3. GitHub Work (This Validation Wave)', H1))
story.append(Paragraph(
    'Every fix followed the issue-first workflow: a structured issue stated the '
    'problem, context, scope, acceptance criteria and validation requirements; '
    'a dedicated branch implemented it; a pull request mapped each acceptance '
    'criterion to evidence; and the merge was followed by post-merge '
    'verification on main. One issue (#87) was created from a false premise, '
    'retracted with published evidence and closed as not-planned — recorded '
    'here because honesty about mistakes is part of the standard.', BODY))
work = [
    header_row(['Item', 'Type', 'Outcome']),
    [Paragraph('#87 branch filter', CELL), Paragraph('Retracted', WARN_S),
     Paragraph('Closed not_planned with git-blob-sha evidence', CELL)],
    [Paragraph('#88 e2e gate self-containment', CELL), Paragraph('Fixed', PASS_S),
     Paragraph('PR #94 merged; gate builds its own binary; portable paths', CELL)],
    [Paragraph('#89 AI-artifact removal', CELL), Paragraph('Fixed', PASS_S),
     Paragraph('PR #95 merged; 18 files, 1,450 lines removed', CELL)],
    [Paragraph('#90 URL-as-directory defect', CELL), Paragraph('Fixed', PASS_S),
     Paragraph('PR #93 merged; loud rejection, 7 new tests', CELL)],
    [Paragraph('#91 CLI HTTP registry', CELL), Paragraph('Feature', PASS_S),
     Paragraph('PR #96 merged; 5 verbs, auth, tenancy, 9 integration tests', CELL)],
    [Paragraph('#97 dashboard live mode', CELL), Paragraph('Fixed', PASS_S),
     Paragraph('PR #98 merged; browser-verified against live service', CELL)],
    [Paragraph('#92 README drift', CELL), Paragraph('Fixed', PASS_S),
     Paragraph('PR #99 merged; counts re-verified by running the suite', CELL)],
    [Paragraph('Final state', CELL), Paragraph('Clean', PASS_S),
     Paragraph('0 open issues, 0 open PRs, only main remains', CELL)],
]
story.append(styled_table(work, [2.6, 1.0, 5.1]))

# ── 4. Quality & Testing ────────────────────────────────────────────────
story.append(Paragraph('4. Quality and Testing', H1))
story.append(Paragraph(
    'The suite was executed in this environment and again in a clean-room '
    'clone of main (npm ci, build, lint, test, gate) to simulate a new '
    'developer following the README. Both runs are green. Per-package counts '
    'below are from the final merged tree; the delta since the previous '
    'documented count (669) is the CLI HTTP-registry integration suite plus '
    'the FFI and generator additions of the 0.2.1 wave.', BODY))
tests = [
    header_row(['Package', 'Tests', 'Focus']),
    [Paragraph('bridge-core', CELL), Paragraph('154', CELL_B),
     Paragraph('Compiler pipeline, property-based + fuzz harnesses', CELL)],
    [Paragraph('bridge-cli', CELL), Paragraph('113', CELL_B),
     Paragraph('All commands, HTTP registry integration (live service)', CELL)],
    [Paragraph('bridge-compat', CELL), Paragraph('101', CELL_B),
     Paragraph('Classification matrix, gates, impact', CELL)],
    [Paragraph('bridge-serialization', CELL), Paragraph('112', CELL_B),
     Paragraph('Cross-language golden vectors', CELL)],
    [Paragraph('bridge-registry-service', CELL), Paragraph('78', CELL_B),
     Paragraph('Auth, tenancy, signing, rate limits, drivers', CELL)],
    [Paragraph('bridge-registry', CELL), Paragraph('65', CELL_B),
     Paragraph('Content-addressed store semantics', CELL)],
    [Paragraph('bridge-generators', CELL), Paragraph('32', CELL_B),
     Paragraph('Six backends, deterministic output, adversarial fixtures', CELL)],
    [Paragraph('bridge-lsp', CELL), Paragraph('33', CELL_B),
     Paragraph('JSON-RPC over stdio', CELL)],
    [Paragraph('bridge-ffi', CELL), Paragraph('11', CELL_B),
     Paragraph('C ABI wrappers, WASM', CELL)],
]
story.append(styled_table(tests, [2.4, 0.9, 5.4]))
story.append(Spacer(1, 4))
story.append(Paragraph(
    'The 25-step acceptance gate walks the real binaries: version and doctor '
    'contract, project scaffolding, validation of good and bad input, '
    'formatting, lint, generation for four languages, TypeScript strict '
    'type-check plus runtime import of generated code, diff classification, '
    'check gating, impact walking, the full registry lifecycle '
    '(publish, versions, inspect, pull, search) and the self-contained release '
    'binary leg. Its steps now build their own binary, so a fresh clone cannot '
    'produce a false failure.', BODY))

# ── 5. Runtime Validation ───────────────────────────────────────────────
story.append(Paragraph('5. Runtime Validation', H1))
story.append(Paragraph(
    'Beyond unit and integration tests, the product was driven as a user. The '
    'registry service was booted with a static-token credential and verified '
    'to fail closed without one: unauthenticated reads receive 401, wrong '
    'tokens are rejected, and cross-tenant requests are indistinguishable from '
    'unknown routes, exactly as the tenancy design requires. The CLI then '
    'published real example contracts over HTTP with tenancy coordinates, and '
    'a second process pulled byte-identical canonical IR back — the '
    'content-addressing guarantee holds across the wire.', BODY))
story.append(Paragraph(
    'The dashboard was exercised in a real browser in both modes. Demo mode '
    'renders the deterministic seed dataset with an honest disclosure banner, '
    'and every interactive element — scope combobox, search, filters, copy '
    'buttons, tabs, breadcrumb navigation — responds. Live mode, rebuilt in '
    'this pass, now renders real data: the overview computed live verdicts '
    'from the diff route, the contracts table listed the contracts published '
    'seconds earlier, the graph page rendered with a truthful empty-edges '
    'state for contracts that have no consumers, and the audit page showed the '
    'actual publish entries with working filters. A production dashboard build '
    'fails fast with an actionable message when its server-side credential or '
    'discovery configuration is missing, rather than silently serving demo '
    'data or a bare error digest.', BODY))
story.append(Paragraph(
    'Finally, a clean-room clone of main was installed, built, tested and gated '
    'from scratch (bun packaged the release binary; the gate ran 25/25). This '
    'is the strongest evidence that the repository is self-contained: no '
    'machine-specific paths, no pre-built artifacts required, no undocumented '
    'steps.', BODY))

# ── 6. Security ─────────────────────────────────────────────────────────
story.append(Paragraph('6. Security', H1))
story.append(Paragraph(
    'The full git history was scanned for token patterns, API keys and private '
    'key material: nothing was found. An early-commit .env contains only a '
    'local SQLite file path, confirming the earlier issue closure. The '
    'registry service fails closed without credentials, verifies an ed25519 '
    'artifact signature before parsing publish payloads, asserts a declared '
    'content hash against the actual canonical hash so tampered payloads are '
    'rejected before storage, rate-limits unauthenticated floods without '
    'letting them evict audit history, and never leaks cross-tenant existence. '
    'The new CLI HTTP layer sends bearer tokens only in the Authorization '
    'header, never logs or echoes them (asserted by test), and the dashboard '
    'keeps its credential server-side where it cannot reach the browser '
    'bundle. The CLI also no longer accepts URL-shaped registry roots as '
    'filesystem paths, closing a path-injection footgun.', BODY))

# ── 7. Repository Hygiene ───────────────────────────────────────────────
story.append(Paragraph('7. Repository Hygiene', H1))
story.append(Paragraph(
    'The repository now contains only intentional product artifacts. Eighteen '
    'committed AI-development files (issue/PR automation scripts, body dumps, '
    'a verifier that referenced a deleted worktree and crashed as committed) '
    'were removed after verifying no tracked file referenced them. Every '
    'markdown file was classified: durable documentation is kept and current; '
    'nothing unfinished hides in task logs, because the unfinished work those '
    'logs described was converted into issues and completed first. Twenty-seven '
    'merged branches were deleted from the remote; only main remains, with a '
    'linear, meaningfully-worded commit history and no secrets. The e2e gate '
    'script lost its last machine-specific paths, so the repository is '
    'portable by construction rather than by convention.', BODY))

# ── 8. Documentation ────────────────────────────────────────────────────
story.append(Paragraph('8. Documentation', H1))
story.append(Paragraph(
    'The README is recruiter-ready and was reconciled with reality: test '
    'counts (699 across nine packages) were re-measured immediately before the '
    'documentation PR, the version headline matches the 0.2.1 workspace '
    'lockstep, the thirty-second walkthrough reproduces as printed, and the '
    'quick-start commands were executed verbatim in a scratch directory (init, '
    'validate, generate, doctor — all exit 0). The registry section documents '
    'both the local and the HTTP registry workflow with real commands. The '
    'dashboard README now documents the verified live-mode configuration '
    '(server-side token, org/project discovery, the admin-role requirement for '
    'the audit page) instead of an aspirational one. The docs/ set (IDL '
    'reference, architecture, compatibility, impact, events, RPC, '
    'serialization, testing, roadmap) was verified current in the 0.2.0 '
    'documentation-sync pass and spot-checked here.', BODY))

# ── 9. Known Limitations & Accepted Risks ───────────────────────────────
story.append(Paragraph('9. Known Limitations and Accepted Risks', H1))
limits = [
    header_row(['Item', 'Status', 'Mitigation / Next Step']),
    [Paragraph('GitHub Actions billing lock (account-level)', CELL),
     Paragraph('OPEN', FAIL_S),
     Paragraph('Owner lifts the Actions spending limit; then CI runs on push '
               'to main and the v0.2.1 tag exercises the release pipeline. '
               'Until then, verify locally exactly as documented.', CELL)],
    [Paragraph('Generated-language bindings not recorded by the service', CELL),
     Paragraph('Accepted', WARN_S),
     Paragraph('Dashboard language badges are honestly empty in live mode; a '
               'future publish-metadata field can restore them.', CELL)],
    [Paragraph('Signed publish (ed25519) not yet wired into the CLI', CELL),
     Paragraph('Accepted', WARN_S),
     Paragraph('Service supports required mode; CLI HTTP publish currently '
               'targets optional-mode services. Follow-up issue recommended.', CELL)],
    [Paragraph('CI branch filter claim retracted (#87)', CELL),
     Paragraph('Closed', PASS_S),
     Paragraph('Filter verified correct via git-blob hashing; documented to '
               'keep the record honest.', CELL)],
]
story.append(styled_table(limits, [3.0, 1.0, 4.7]))

# ── 10. Release Readiness Checklist ─────────────────────────────────────
story.append(Paragraph('10. Release Readiness Checklist', H1))
checklist = [
    header_row(['Criterion', 'State']),
    [Paragraph('All major user journeys work in the real application', CELL),
     Paragraph('VERIFIED', PASS_S)],
    [Paragraph('APIs: auth, authz, validation, errors, idempotency', CELL),
     Paragraph('VERIFIED', PASS_S)],
    [Paragraph('Data integrity: immutability, content addressing, tamper tripwire', CELL),
     Paragraph('VERIFIED', PASS_S)],
    [Paragraph('Security audit complete; no secrets in history', CELL),
     Paragraph('VERIFIED', PASS_S)],
    [Paragraph('Accessibility: landmarks, labels, keyboard, focus, contrast', CELL),
     Paragraph('VERIFIED', PASS_S)],
    [Paragraph('Tests pass (699/699), lint 0 warnings, builds clean', CELL),
     Paragraph('VERIFIED', PASS_S)],
    [Paragraph('Clean installation from a fresh clone', CELL),
     Paragraph('VERIFIED', PASS_S)],
    [Paragraph('Regression suite green after every merged change', CELL),
     Paragraph('VERIFIED', PASS_S)],
    [Paragraph('Documentation reflects reality (README executed, not assumed)', CELL),
     Paragraph('VERIFIED', PASS_S)],
    [Paragraph('Repository clean: no AI dumps, no dead code, no orphan branches', CELL),
     Paragraph('VERIFIED', PASS_S)],
    [Paragraph('CI green on GitHub', CELL),
     Paragraph('PENDING BILLING', FAIL_S)],
    [Paragraph('v0.2.1 tag cut through the release pipeline', CELL),
     Paragraph('PENDING BILLING', FAIL_S)],
]
story.append(styled_table(checklist, [5.6, 2.1]))
story.append(Spacer(1, 8))
story.append(Paragraph(
    'Bottom line: every engineering criterion for customer use is met and '
    'evidenced. The two open items are organizational, not technical — lift '
    'the Actions spending limit, let the pipeline validate itself on the next '
    'push, cut v0.2.1, and begin onboarding.', BODY))

doc = SimpleDocTemplate(
    OUT, pagesize=A4,
    leftMargin=22*mm, rightMargin=22*mm, topMargin=20*mm, bottomMargin=20*mm,
    title='Bridge QA and Production Readiness Report',
    author='Z.ai',
    subject='Final validation of the Bridge polyglot contract compiler platform (v0.2.1)',
    creator='Z.ai',
)
doc.build(story)
print('body built:', OUT)
