/**
 * @bridge/serialization — cross-language serialization for Bridge values.
 *
 * One value model, three formats, byte-identical across languages:
 *  - canonical JSON   (see ./canonical)
 *  - MessagePack      (see ./msgpack) — pure TS encoder/decoder
 *  - CBOR             (see ./cbor) — pure TS RFC 8949 subset
 *
 * The cross-language contract lives in docs/SERIALIZATION.md; the golden
 * fixtures that every runtime (Go / Rust / Python) verifies live in
 * ./vectors/vectors.json (committed hex, generated by ./gen-vectors).
 */
export {
  BridgeMap,
  BridgeSet,
  BridgeTimestamp,
  BridgeValue,
  MAX_I64,
  MAX_U64,
  MIN_I64,
  compareValues,
  sortedMapKeys,
  valueEquals,
  valueFamily,
} from './types';
export { canonicalJson } from './canonical';
export { encodeMsgpack, decodeMsgpack } from './msgpack';
export { encodeCbor, decodeCbor } from './cbor';
export { valueFromTagged, TaggedValue } from './tagged';
